---
title: "JSC370 Final Project"
author: "Wise Chua"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.

```{r setup, echo=FALSE, message = FALSE}
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval = TRUE,
  echo = FALSE,
  cache = FALSE,
  include = TRUE)

library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(gtrendsR)
library(knitr)
library(kableExtra)
library(gganimate)
library(viridis)
```

```{r, warning=FALSE, echo=FALSE, include=TRUE}
`2022 Qatar World Cup 5 Search Keywords` <- c("world cup 2022", "world cup", "2022 world cup", "qatar world cup", "fifa world cup")
`2022 Qatar World Cup 10 Related Search Words` <- c("fifa", "fifa world cup 2022", "fifa 2022", "2022 world cup schedule", "qatar 2022 world cup")
`2022 Qatar World Cup 10 Related Search Words1` <- c("world cup 2022 fixtures", "world cup football 2022", "world cup 2022 live", "world cup live", "world cup table 2022")

`2022 Beijing Olympic Games 5 Search Keywords` <- c("2022 winter olympic", "olympic games beijing 2022", "olympic games 2022", "beijing olympics 2022", "winter olympic games")
`2022 Beijing Olympic Games 10 Related Search Words` <- c("olympics 2022", "olympics", "winter games 2022", "winter olympics", "olympic games")

`2022 Beijing Olympic Games 10 Related Search Words1` <- c("2022 winter olympic games", "winter olympic games 2022", "olympic medals 2022", "winter olympic medal 2022", "beijing 2022")

`2022 Birmingham Commonwealth Games 5 Search Keywords` <- c("2022 birmingham commonwealth games", "2022 birmingham commonwealth", "commonwealth games", "commonwealth games 2022", "2022 commonwealth games")
`2022 Birmingham Commonwealth Games 10 Related Search Words` <- c("birmingham commonwealth games 2022", "birmingham games", "birmingham games 2022", "commonwealth games 2022 india", "commonwealth games 2022 table")
`2022 Birmingham Commonwealth Games 10 Related Search Words1` <- c("birmingham 2022 commonwealth games india", "commonwealth games medal tally 2022", "commonwealth games medal tally", "commonwealth games medal table", "commonwealth games 2022 medals")

`2022 League of Legend World Championship 5 Search Keywords` <- c("2022 league of legends world championship", "2022 league of legends", "2022 lol world championship", "2022 lol worlds", "lol worlds championship")
`2022 League of Legend World Championship 10 Related Search Words` <- c("league of legends worlds", "league of legends worlds 2022", "worlds 2022", "lol world championship 2022", "league of legends world championship 2022 tickets")
`2022 League of Legend World Championship 10 Related Search Words1` <- c("league of legends champions", "league of legends world championship prize pool", "league of legends world championship 2022 prize pool", "league of legends world championship 2022 schedule", "worlds league of legends")

`2022 The International Dota 2 5 Search Keywords` <- c("the international dota 2 championship", "2022 the international dota 2 championship", "dota 2 championship", "the international dota 2", "dota the international 2022")
`2022 The International Dota 2 10 Related Search Words` <- c("dota 2 world championship", "dota 2 championship 2022", "dota 2 world championship 2022", "dota 2 championship prize", "the international 2022 dota 2")
`2022 The International Dota 2 10 Related Search Words1` <- c("dota 2 international 2022", "the international 2022", "international dota 2 2022", "dota 2 liquipedia", "the international dota 2 championship")

df <- rbind(`2022 Qatar World Cup 5 Search Keywords`, `2022 Qatar World Cup 10 Related Search Words`, `2022 Qatar World Cup 10 Related Search Words1`, `2022 Beijing Olympic Games 5 Search Keywords`, `2022 Beijing Olympic Games 10 Related Search Words`, `2022 Beijing Olympic Games 10 Related Search Words1`, `2022 Birmingham Commonwealth Games 5 Search Keywords`, `2022 Birmingham Commonwealth Games 10 Related Search Words`, `2022 Birmingham Commonwealth Games 10 Related Search Words1`, `2022 League of Legend World Championship 5 Search Keywords`, `2022 League of Legend World Championship 10 Related Search Words`, `2022 League of Legend World Championship 10 Related Search Words1`, `2022 The International Dota 2 5 Search Keywords`, `2022 The International Dota 2 10 Related Search Words`, `2022 The International Dota 2 10 Related Search Words1`)
```


```{r, warning=FALSE, echo=FALSE, include=TRUE}
rownames(df) <- c("2022 Qatar World Cup 5 Search Keywords", "2022 Qatar World Cup 10 Related Search Words", "", "2022 Beijing Olympic Games 5 Search Keywords", "2022 Beijing Olympic Games 10 Related Search Words", "", "2022 Birmingham Commonwealth Games 5 Search Keywords", "2022 Birmingham Commonwealth Games 10 Related Search Words", "", "2022 League of Legend World Championship 5 Search Keywords", "2022 League of Legend World Championship 10 Related Search Words", "", "2022 The International Dota 2 5 Search Keywords", "2022 The International Dota 2 10 Related Search Words", "")
```


```{r, warning=FALSE, echo=FALSE}
kable(df, caption = "Table 1: Keywords to Search on Google Trends for Each Sports Events") %>% kable_classic(full_width = TRUE, html_font = "Cambria", font_size=14)
```

```{r, warning=FALSE, echo=FALSE, include=TRUE, message=FALSE}
world_cup_1 <- gtrends(c("world cup 2022", "world cup", "2022 world cup", "qatar world cup", "fifa world cup"), time = "2022-01-01 2022-12-31", gprop = c("web"))
```

```{r, warning=FALSE, echo=FALSE, include=TRUE, message=FALSE}
world_cup_2 <- gtrends(c("fifa", "fifa world cup 2022", "fifa 2022", "2022 world cup schedule", "qatar 2022 world cup"), time = "2022-01-01 2022-12-31", gprop = c("web"))

world_cup_3 <- gtrends(c("world cup 2022 fixtures", "world cup football 2022", "world cup 2022 live", "world cup live", "world cup table 2022"), time = "2022-01-01 2022-12-31", gprop = c("web"))
```

```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE, message=FALSE}
world_cup_interest_over_time <- bind_rows(world_cup_1$interest_over_time, world_cup_2$interest_over_time, world_cup_3$interest_over_time)
world_cup_interest_over_time$hits[world_cup_interest_over_time$hits == '<1'] <- 0
world_cup_interest_over_time$hits<- as.integer(world_cup_interest_over_time$hits)
world_cup_interest_over_time$date<- as.Date(world_cup_interest_over_time$date)
world_cup_interest_over_time_summary <- world_cup_interest_over_time %>% 
  group_by(date) %>% 
  summarise(hits = mean(hits, na.rm = TRUE))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
world_cup_interest_by_country <- bind_rows(world_cup_1$interest_by_country, world_cup_2$interest_by_country, world_cup_3$interest_by_country)
world_cup_interest_by_country$hits[world_cup_interest_by_country$hits == '<1'] <- 0
world_cup_interest_by_country$hits <- as.integer(world_cup_interest_by_country$hits)
world_cup_interest_by_country <- world_cup_interest_by_country %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(world_cup_interest_by_country) <- c("Countries", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
world_cup_interest_by_dma <- bind_rows(world_cup_1$interest_by_dma, world_cup_2$interest_by_dma, world_cup_3$interest_by_dma)
world_cup_interest_by_dma$hits[world_cup_interest_by_dma$hits == '<1'] <- 0
world_cup_interest_by_dma$hits <- as.integer(world_cup_interest_by_dma$hits)
world_cup_interest_by_dma <- world_cup_interest_by_dma %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(world_cup_interest_by_dma) <- c("District", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
world_cup_interest_by_city <- bind_rows(world_cup_1$interest_by_city, world_cup_2$interest_by_city, world_cup_3$interest_by_city)
world_cup_interest_by_city$hits[world_cup_interest_by_city$hits == '<1'] <- 0
world_cup_interest_by_city$hits <- as.integer(world_cup_interest_by_city$hits)
world_cup_interest_by_city <- world_cup_interest_by_city %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(world_cup_interest_by_city) <- c("City", "Hits")
```

```{r, warning=FALSE, echo=FALSE}
kables(
  list(
    kable(head(world_cup_interest_by_city)) ,
    kable(head(world_cup_interest_by_country)) ,
    kable(head(world_cup_interest_by_dma)) 
  ),
  caption = 'Table 2: First six rows of the World Cup Data by City, Country and District.'
)%>% kable_classic(full_width = TRUE, html_font = "Cambria", font_size=14)
```








```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
olympic_games_1 <- gtrends(c("2022 winter olympic", "olympic games beijing 2022", "olympic games 2022", "beijing olympics 2022", "winter olympic games"), time = "2022-01-01 2022-12-31", gprop = c("web"))
```

```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
olympic_games_2 <- gtrends(c("olympics 2022", "olympics", "winter games 2022", "winter olympics", "olympic games"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
olympic_games_3 <- gtrends(c("2022 winter olympic games", "winter olympic games 2022", "olympic medals 2022", "winter olympic medal 2022", "beijing 2022"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```



```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
olympic_games_interest_over_time <- bind_rows(olympic_games_1$interest_over_time, olympic_games_2$interest_over_time, olympic_games_3$interest_over_time)
olympic_games_interest_over_time$hits[olympic_games_interest_over_time$hits == '<1'] <- 0
olympic_games_interest_over_time$hits<- as.integer(olympic_games_interest_over_time$hits)
olympic_games_interest_over_time$date<- as.Date(olympic_games_interest_over_time$date)
olympic_games_interest_over_time_summary <- olympic_games_interest_over_time %>% 
  group_by(date) %>% 
  summarise(hits = mean(hits, na.rm = TRUE))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
olympic_games_interest_by_country <- bind_rows(olympic_games_1$interest_by_country, olympic_games_2$interest_by_country, olympic_games_3$interest_by_country)
olympic_games_interest_by_country$hits[olympic_games_interest_by_country$hits == '<1'] <- 0
olympic_games_interest_by_country$hits <- as.integer(olympic_games_interest_by_country$hits)
olympic_games_interest_by_country <- olympic_games_interest_by_country %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(olympic_games_interest_by_country) <- c("Countries", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
olympic_games_2$interest_by_dma$hits <- as.integer(olympic_games_2$interest_by_dma$hits)
olympic_games_interest_by_dma <- bind_rows(olympic_games_1$interest_by_dma, olympic_games_2$interest_by_dma, olympic_games_3$interest_by_dma)
olympic_games_interest_by_dma$hits[olympic_games_interest_by_dma$hits == '<1'] <- 0
olympic_games_interest_by_dma$hits <- as.integer(olympic_games_interest_by_dma$hits)
olympic_games_interest_by_dma <- olympic_games_interest_by_dma %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(olympic_games_interest_by_dma) <- c("District", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
olympic_games_interest_by_city <- bind_rows(olympic_games_1$interest_by_city, olympic_games_2$interest_by_city, olympic_games_3$interest_by_city)
olympic_games_interest_by_city$hits[olympic_games_interest_by_city$hits == '<1'] <- 0
olympic_games_interest_by_city$hits <- as.integer(olympic_games_interest_by_city$hits)
olympic_games_interest_by_city <- olympic_games_interest_by_city %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(olympic_games_interest_by_city) <- c("City", "Hits")
```

```{r, warning=FALSE, echo=FALSE}
kables(
  list(
    kable(head(olympic_games_interest_by_city)),
    kable(head(olympic_games_interest_by_country)),
    kable(head(olympic_games_interest_by_dma))
  ),
  caption = 'Table 3: First six rows of the Olympic Games Data by City, Country and District.'
) %>% kable_classic(full_width = TRUE, html_font = "Cambria", font_size=14)
```

```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
commonwealth_games_1 <- gtrends(c("2022 birmingham commonwealth games", "2022 birmingham commonwealth", "commonwealth games", "commonwealth games 2022", "2022 commonwealth games"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
commonwealth_games_2 <- gtrends(c("birmingham commonwealth games 2022", "birmingham games", "birmingham games 2022", "commonwealth games 2022 india", "commonwealth games 2022 table"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
commonwealth_games_3 <- gtrends(c("birmingham 2022 commonwealth games india", "commonwealth games medal tally 2022", "commonwealth games medal tally", "commonwealth games medal table", "commonwealth games 2022 medals"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```

```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
commonwealth_games_interest_over_time <- bind_rows(commonwealth_games_1$interest_over_time, commonwealth_games_2$interest_over_time, commonwealth_games_3$interest_over_time)
commonwealth_games_interest_over_time$hits[commonwealth_games_interest_over_time$hits == '<1'] <- 0
commonwealth_games_interest_over_time$hits<- as.integer(commonwealth_games_interest_over_time$hits)
commonwealth_games_interest_over_time$date<- as.Date(commonwealth_games_interest_over_time$date)
commonwealth_games_interest_over_time_summary <- commonwealth_games_interest_over_time %>% 
  group_by(date) %>% 
  summarise(hits = mean(hits, na.rm = TRUE))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
commonwealth_games_interest_by_country <- bind_rows(commonwealth_games_1$interest_by_country, commonwealth_games_2$interest_by_country, commonwealth_games_3$interest_by_country)
commonwealth_games_interest_by_country$hits[commonwealth_games_interest_by_country$hits == '<1'] <- 0
commonwealth_games_interest_by_country$hits <- as.integer(commonwealth_games_interest_by_country$hits)
commonwealth_games_interest_by_country <- commonwealth_games_interest_by_country %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(commonwealth_games_interest_by_country) <- c("Countries", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
commonwealth_games_2$interest_by_dma$hits[commonwealth_games_2$interest_by_dma$hits == ' '] <- 0
commonwealth_games_2$interest_by_dma$hits <- as.integer(commonwealth_games_2$interest_by_dma$hits)
commonwealth_games_interest_by_dma <- bind_rows(commonwealth_games_1$interest_by_dma, commonwealth_games_2$interest_by_dma, commonwealth_games_3$interest_by_dma)
commonwealth_games_interest_by_dma$hits[commonwealth_games_interest_by_dma$hits == '<1'] <- 0
commonwealth_games_interest_by_dma$hits <- as.integer(commonwealth_games_interest_by_dma$hits)
commonwealth_games_interest_by_dma <- commonwealth_games_interest_by_dma %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(commonwealth_games_interest_by_dma) <- c("District", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
commonwealth_games_interest_by_city <- bind_rows(commonwealth_games_1$interest_by_city, commonwealth_games_2$interest_by_city, commonwealth_games_3$interest_by_city)
commonwealth_games_interest_by_city$hits[commonwealth_games_interest_by_city$hits == '<1'] <- 0
commonwealth_games_interest_by_city$hits <- as.integer(commonwealth_games_interest_by_city$hits)
commonwealth_games_interest_by_city <- commonwealth_games_interest_by_city %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(commonwealth_games_interest_by_city) <- c("City", "Hits")
```

```{r, warning=FALSE, echo=FALSE}
kables(
  list(
    kable(head(commonwealth_games_interest_by_city)),
    kable(head(commonwealth_games_interest_by_country)),
    kable(head(commonwealth_games_interest_by_dma))
  ),
  caption = 'Table 4: First six rows of the Commonwealth Games Data by City, Country and District.'
) %>% kable_classic(full_width = TRUE, html_font = "Cambria", font_size=14)
```



```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
lol_games_1 <- gtrends(c("2022 league of legends world championship", "2022 league of legends", "2022 lol world championship", "2022 lol worlds", "lol worlds championship"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
lol_games_2 <- gtrends(c("league of legends worlds", "league of legends worlds 2022", "worlds 2022", "lol world championship 2022", "league of legends world championship 2022 tickets"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
lol_games_3 <- gtrends(c("league of legends champions", "league of legends world championship prize pool", "league of legends world championship 2022 prize pool", "league of legends world championship 2022 schedule", "worlds league of legends"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
lol_games_interest_over_time <- bind_rows(lol_games_1$interest_over_time, lol_games_2$interest_over_time, lol_games_3$interest_over_time)
lol_games_interest_over_time$hits[lol_games_interest_over_time$hits == '<1'] <- 0
lol_games_interest_over_time$hits<- as.integer(lol_games_interest_over_time$hits)
lol_games_interest_over_time$date<- as.Date(lol_games_interest_over_time$date)
lol_games_interest_over_time_summary <- lol_games_interest_over_time %>% 
  group_by(date) %>% 
  summarise(hits = mean(hits, na.rm = TRUE))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
lol_games_1$interest_by_country$hits <- as.integer(lol_games_1$interest_by_country$hits)
lol_games_interest_by_country <- bind_rows(lol_games_1$interest_by_country, lol_games_2$interest_by_country, lol_games_3$interest_by_country)
lol_games_interest_by_country$hits[lol_games_interest_by_country$hits == '<1'] <- 0
lol_games_interest_by_country$hits <- as.integer(lol_games_interest_by_country$hits)
lol_games_interest_by_country <- lol_games_interest_by_country %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(lol_games_interest_by_country) <- c("Countries", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
lol_games_interest_by_dma <- bind_rows(lol_games_1$interest_by_dma, lol_games_2$interest_by_dma, lol_games_3$interest_by_dma)
lol_games_interest_by_dma$hits[lol_games_interest_by_dma$hits == '<1'] <- 0
lol_games_interest_by_dma$hits <- as.integer(lol_games_interest_by_dma$hits)
lol_games_interest_by_dma <- lol_games_interest_by_dma %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(lol_games_interest_by_dma) <- c("District", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
lol_games_interest_by_city <- bind_rows(lol_games_1$interest_by_city, lol_games_2$interest_by_city, lol_games_3$interest_by_city)
lol_games_interest_by_city$hits[lol_games_interest_by_city$hits == '<1'] <- 0
lol_games_interest_by_city$hits <- as.integer(lol_games_interest_by_city$hits)
lol_games_interest_by_city <- lol_games_interest_by_city %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(lol_games_interest_by_city) <- c("City", "Hits")
```

```{r, warning=FALSE, echo=FALSE}
kables(
  list(
    kable(head(lol_games_interest_by_city)),
    kable(head(lol_games_interest_by_country)),
    kable(head(lol_games_interest_by_dma))
  ),
  caption = 'Table 5: First six rows of the League of Legends Games Data by City, Country and District.'
) %>% kable_classic(full_width = TRUE, html_font = "Cambria", font_size=14)
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
dota_games_1 <- gtrends(c("the international dota 2 championship", "2022 the international dota 2 championship", "dota 2 championship", "the international dota 2", "dota the international 2022"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
dota_games_2 <- gtrends(c("dota 2 world championship", "dota 2 championship 2022", "dota 2 world championship 2022", "dota 2 championship prize", "the international 2022 dota 2"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
dota_games_3 <- gtrends(c("dota 2 international 2022", "the international 2022", "international dota 2 2022", "dota 2 liquipedia", "the international dota 2 championship"), time = '2022-01-01 2022-12-31', gprop = c("web"))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
dota_games_1$interest_over_time$hits <- as.integer(dota_games_1$interest_over_time$hits)
dota_games_2$interest_over_time$hits <- as.integer(dota_games_2$interest_over_time$hits)
dota_games_3$interest_over_time$hits <- as.integer(dota_games_3$interest_over_time$hits)
dota_games_interest_over_time <- bind_rows(dota_games_1$interest_over_time, dota_games_2$interest_over_time, dota_games_3$interest_over_time)
dota_games_interest_over_time$hits[dota_games_interest_over_time$hits == '<1'] <- 0
dota_games_interest_over_time$hits<- as.integer(dota_games_interest_over_time$hits)
dota_games_interest_over_time$date<- as.Date(dota_games_interest_over_time$date)
dota_games_interest_over_time_summary <- dota_games_interest_over_time %>% 
  group_by(date) %>% 
  summarise(hits = mean(hits, na.rm = TRUE))
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
dota_games_2$interest_by_country$hits <- as.integer(dota_games_2$interest_by_country$hits)
dota_games_3$interest_by_country$hits <- as.integer(dota_games_3$interest_by_country$hits)
dota_games_interest_by_country <- bind_rows(dota_games_1$interest_by_country, dota_games_2$interest_by_country, dota_games_3$interest_by_country)
dota_games_interest_by_country$hits[dota_games_interest_by_country$hits == '<1'] <- 0
dota_games_interest_by_country$hits <- as.integer(dota_games_interest_by_country$hits)
dota_games_interest_by_country <- dota_games_interest_by_country %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(dota_games_interest_by_country) <- c("Countries", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
dota_games_interest_by_dma <- bind_rows(dota_games_1$interest_by_dma, dota_games_2$interest_by_dma, dota_games_3$interest_by_dma)
dota_games_interest_by_dma$hits[dota_games_interest_by_dma$hits == '<1'] <- 0
dota_games_interest_by_dma$hits <- as.integer(dota_games_interest_by_dma$hits)
dota_games_interest_by_dma <- dota_games_interest_by_dma %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(dota_games_interest_by_dma) <- c("District", "Hits")
```


```{r, warning=FALSE, echo=FALSE, include=TRUE, eval=TRUE}
dota_games_interest_by_city <- bind_rows(dota_games_1$interest_by_city, dota_games_2$interest_by_city, dota_games_3$interest_by_city)
dota_games_interest_by_city$hits[dota_games_interest_by_city$hits == '<1'] <- 0
dota_games_interest_by_city$hits <- as.integer(dota_games_interest_by_city$hits)
dota_games_interest_by_city <- dota_games_interest_by_city %>% 
  group_by(location) %>% 
  summarise(hits = mean(hits, na.rm = TRUE)) %>% 
  arrange(desc(hits))
colnames(dota_games_interest_by_city) <- c("City", "Hits")
```

```{r, warning=FALSE, echo=FALSE,}
kables(
  list(
    kable(head(dota_games_interest_by_city)),
    kable(head(dota_games_interest_by_country)),
    kable(head(dota_games_interest_by_dma))
  ),
  caption = 'Table 6: First six rows of the Dota Games Data by City, Country and District.'
) %>% kable_classic(full_width = TRUE, html_font = "Cambria", font_size=14)
```

```{r, warning=FALSE, echo=FALSE}
interest_by_city_list <- list(world_cup_interest_by_city, olympic_games_interest_by_city, commonwealth_games_interest_by_city, lol_games_interest_by_city, dota_games_interest_by_city)
interest_by_city_combine <- interest_by_city_list %>% reduce(full_join, by='City')
interest_by_city_combine <- data.frame(interest_by_city_combine)
interest_by_city_combine$Hits.x[is.nan(interest_by_city_combine$Hits.x)]<-NA
interest_by_city_combine$Hits.y[is.nan(interest_by_city_combine$Hits.y)]<-NA
interest_by_city_combine$Hits.x.x[is.nan(interest_by_city_combine$Hits.x.x)]<-NA
interest_by_city_combine$Hits.y.y[is.nan(interest_by_city_combine$Hits.y.y)]<-NA
interest_by_city_combine$Hits[is.nan(interest_by_city_combine$Hits)]<-NA
interest_by_city_combine <- filter(interest_by_city_combine,rowSums(is.na(interest_by_city_combine)) != ncol(interest_by_city_combine) - 1)
colnames(interest_by_city_combine) <- c("City", "World Cup Hits", "Olympic Games Hits", "Commonwealth Games Hits", "League of Legends Hits", "Dota 2 Hits")
```

```{r, warning=FALSE, echo=FALSE}
interest_by_country_list <- list(world_cup_interest_by_country, olympic_games_interest_by_country, commonwealth_games_interest_by_country, lol_games_interest_by_country, dota_games_interest_by_country)
interest_by_country_combine <- interest_by_country_list %>% reduce(full_join, by='Countries')
interest_by_country_combine <- data.frame(interest_by_country_combine)
interest_by_country_combine$Hits.x[is.nan(interest_by_country_combine$Hits.x)] <- NA
interest_by_country_combine$Hits.y[is.nan(interest_by_country_combine$Hits.y)] <- NA
interest_by_country_combine$Hits.x.x[is.nan(interest_by_country_combine$Hits.x.x)] <- NA
interest_by_country_combine$Hits.y.y[is.nan(interest_by_country_combine$Hits.y.y)] <- NA
interest_by_country_combine$Hits[is.nan(interest_by_country_combine$Hits)] <- NA
interest_by_country_combine <- filter(interest_by_country_combine,rowSums(is.na(interest_by_country_combine)) != ncol(interest_by_country_combine) - 1)
colnames(interest_by_country_combine) <- c("Country", "World Cup Hits", "Olympic Games Hits", "Commonwealth Games Hits", "League of Legends Hits", "Dota 2 Hits")
```

```{r, warning=FALSE, echo=FALSE}
interest_by_dma_list <- list(world_cup_interest_by_dma, olympic_games_interest_by_dma, commonwealth_games_interest_by_dma, lol_games_interest_by_dma, dota_games_interest_by_dma)
interest_by_dma_combine <- interest_by_dma_list %>% reduce(full_join, by='District')
interest_by_dma_combine <- data.frame(interest_by_dma_combine)
interest_by_dma_combine$Hits.x[is.nan(interest_by_dma_combine$Hits.x)] <- NA
interest_by_dma_combine$Hits.y[is.nan(interest_by_dma_combine$Hits.y)] <- NA
interest_by_dma_combine$Hits.x.x[is.nan(interest_by_dma_combine$Hits.x.x)] <- NA
interest_by_dma_combine$Hits.y.y[is.nan(interest_by_dma_combine$Hits.y.y)] <- NA
interest_by_dma_combine$Hits[is.nan(interest_by_dma_combine$Hits)] <- NA
interest_by_dma_combine <- filter(interest_by_dma_combine,rowSums(is.na(interest_by_dma_combine)) != ncol(interest_by_dma_combine) - 1)
colnames(interest_by_dma_combine) <- c("District", "World Cup Hits", "Olympic Games Hits", "Commonwealth Games Hits", "League of Legends Hits", "Dota 2 Hits")
```

```{r, warning=FALSE, echo=FALSE, width=17}
interest_by_city_combine_1 <- filter(interest_by_city_combine,rowSums(is.na(interest_by_city_combine)) <= ncol(interest_by_city_combine) - 3)
interest_by_city_combine_1[is.na(interest_by_city_combine_1)] <- 0
interest_by_city_combine_1 %>% 
  pivot_longer(names_to = "Games", values_to = "Hits", cols = c(2:6)) %>% 
  ggplot(mapping = aes(x = fct_infreq(City, Hits), y= Hits, fill = Games)) + 
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3") + 
  scale_x_discrete(guide = guide_axis(n.dodge=4)) +
  labs(
    title = "Hits of Each Sports Event by City",
    x = "City", y = "Hits", fill = "Sport Events",
    caption = "Table 7: Cities that has at least 3 values of hits in the 5 sport events"
    )
```

```{r echo=FALSE, warning=FALSE}
interest_by_country_combine_1 <- filter(interest_by_country_combine,rowSums(is.na(interest_by_country_combine)) == ncol(interest_by_country_combine) - 6)
interest_by_country_combine_1 %>% 
  pivot_longer(names_to = "Games", values_to = "Hits", cols = c(2:6)) %>% 
  ggplot(mapping = aes(x = fct_infreq(Country, Hits), y= Hits, fill = Games)) + 
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3") + 
  scale_x_discrete(guide = guide_axis(n.dodge=4)) +
  labs(
    title = "Countries with all Sport Events Search Hits",
    x = "Country", y = "Hits", fill = "Sport Events",
    caption = "Table 8: Countries that has all 5 sport events of search hits"
    )
```

```{r, warning=FALSE, echo=FALSE, warning=FALSE}
interest_by_dma_combine_1 <- filter(interest_by_dma_combine,rowSums(is.na(interest_by_dma_combine)) == ncol(interest_by_dma_combine) - 6)

interest_by_dma_combine_1 <- interest_by_dma_combine_1 %>% pivot_longer(names_to = "Games", values_to = "Hits", cols = c(2:6)) %>% 
  group_by(District) %>% mutate(Hits = Hits, Games = Games, total_Hits = sum(Hits)) %>% arrange(desc(total_Hits)) 
interest_by_dma_combine_1 <- data.frame(interest_by_dma_combine_1) %>% 
  slice_head(n = 50)

interest_by_dma_combine_1 %>% 
  ggplot(mapping = aes(x = fct_infreq(District, Hits), y= Hits, fill = Games)) + 
  geom_bar(stat = "identity") +
  scale_fill_brewer(palette = "Set3") + 
  scale_x_discrete(guide = guide_axis(n.dodge=4)) +
  labs(
    title = "Hits of Each Sports Event by District",
    x = "District", y = "Hits", fill = "Games",
    caption = "Table 9 : Districts that has all 5 sport events of search hits"
    )
```

```{r, warning=FALSE, echo=FALSE}

kables(list(
  kable(summary(world_cup_interest_over_time_summary), caption = "Summary Results for World Cup Search Trend") ,
  kable(summary(olympic_games_interest_over_time_summary), caption = "Summary Results for Olympic Games Search Trend")), caption = "Table 10: Summary Results for All Sport Events Search Trend with Time") %>% kable_classic( html_font = "Cambria", font_size=14)
kables(list(
  kable(summary(commonwealth_games_interest_over_time_summary), caption = "Summary Results for Commonwealth Games Search Trend"),
  kable(summary(lol_games_interest_over_time_summary), caption = " Summary Results for League of Legends Search Trend with Time") ))%>% kable_classic( html_font = "Cambria", font_size=14)
kables(list(
  kable(summary(dota_games_interest_over_time_summary), caption = " Summary Results for League of Legends Search Trend with Time") ))%>% kable_classic( html_font = "Cambria", font_size=14)

```

```{r, warning = FALSE, echo=FALSE, message=FALSE}
interest_over_time_list <- list(world_cup_interest_over_time_summary, olympic_games_interest_over_time_summary, commonwealth_games_interest_over_time_summary, lol_games_interest_over_time_summary, dota_games_interest_over_time_summary)
interest_over_time_combine <- interest_over_time_list %>% reduce(full_join, by='date')
interest_over_time_combine <- data.frame(interest_over_time_combine)
colnames(interest_over_time_combine) <- c("Date", "World Cup Hits", "Olympic Games Hits", "Commonwealth Games Hits", "League of Legends Hits", "Dota 2 Hits")
interest_over_time_combine <- interest_over_time_combine %>% pivot_longer(names_to = "Games", values_to = "Hits", cols = c(2:6))

colnames(interest_over_time_combine) <- c("Date", "Sport Events", "Hits")
```


```{r, warning = FALSE, echo=FALSE, message=FALSE}
interest_over_time_combine %>%
  ggplot(aes(x=Date, y=`Hits`, group=`Sport Events`, color=`Sport Events`)) +
  geom_line() +
  geom_point() +
  scale_color_viridis(discrete = TRUE) +
  ggtitle("Search Trends over Dates in 2022 for Different Sport Events") +
  ylab("Search Hits Trends") +
  labs(fill = "Sport Event") +
  theme_light() +
  transition_reveal(Date)
```

```{r, warning = FALSE, message=FALSE, echo=FALSE}
interest_over_time_combine |> 
  ggplot() + geom_line(mapping = aes(x = Date, y = Hits, colour = `Sport Events`)) +
  # Use facets
  facet_wrap(~ `Sport Events`, nrow = 5) +
  labs(fill = "Sport Event") +
  scale_color_viridis(discrete = TRUE) +
  theme_minimal() 
```
